# Generated by Django 5.2.9 on 2026-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ls_product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ls_variant_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='ls_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='ls_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('quarterly', '3 Months')], max_length=20),
        ),
    ]
