# Generated by Django 5.2.9 on 2026-06-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_chapter_course_domain_chapter_domain'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_quiz_questions', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('mock', 'Mock Exam'), ('chapter_quiz', 'Chapter Quick Quiz')], default='quiz', max_length=15),
        ),
    ]
