# Generated by Django 5.2.9 on 2026-06-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_chapter_fk_and_chapter_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out')], default='in_progress', max_length=15),
        ),
    ]
