# Generated by Django 5.2.9 on 2026-08-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_moduleassessmentresult'),
        ('quiz', '0003_add_time_limit_and_timed_out_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_assessment_questions', to='courses.domain'),
        ),
        migrations.AddField(
            model_name='topic',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='courses.domain'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('mock', 'Mock Exam'), ('chapter_quiz', 'Chapter Quick Quiz'), ('module_assessment', 'Full Module MCQ Assessment'), ('pre_assessment', 'Pre-Assessment'), ('practice_test', 'Practice Test'), ('final_exam', 'Final Exam')], default='quiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='session_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('mock', 'Mock Exam'), ('pre_assessment', 'Pre-Assessment'), ('practice_test', 'Practice Test'), ('final_exam', 'Final Exam')], default='quiz', max_length=20),
        ),
    ]
